version: '3'
services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  postgres:
    image: postgres:12
    environment:
      POSTGRES_DB: rata
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 88888888
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data