"""add user confirmed

Revision ID: 12b8041f84f7
Revises: 6af3fbd2d65a
Create Date: 2023-08-14 18:24:15.959523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12b8041f84f7'
down_revision = '6af3fbd2d65a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
