"""second_migration

Revision ID: bc6167e5ca47
Revises: 7b4142b6d663
Create Date: 2023-07-31 18:22:21.100376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc6167e5ca47'
down_revision = '7b4142b6d663'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
