"""add_in

Revision ID: cac32fa6a514
Revises: acb07ba8abe5
Create Date: 2023-08-11 14:25:50.252698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cac32fa6a514'
down_revision = 'acb07ba8abe5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
