"""3_migration

Revision ID: f75fc6f88359
Revises: bc6167e5ca47
Create Date: 2023-08-01 23:28:33.811261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f75fc6f88359'
down_revision = 'bc6167e5ca47'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
